import { contenu } from './app/contenu';

export const CONTENUS: contenu[] = [
    {
        id: 1,
        titre: 'Welcome to e-covid_2022',
        sous_titre: 'A moroccan platform for covid_19 management ',
        paragraphe: 'The e-covid19 platform is a moroccan platform for covid-19 management. It presents a decision-making assistance tool based on AI aimed to provide real-time social media analysis, automated sentiment analysis and topic modeling.',
        description3: 'description 1',
        button: 'view Video',
        lien:'',
        image: 'description 1',
        phone:'',
        adresse:'',
        email:"",

    },
    {
        id: 2,
        titre: 'An infectious disease caused by the SARS-CoV-2 virus.',
        sous_titre: '',
        paragraphe: 'Most of the symptoms that infected people show are respiratory issues, from simple to severe, and tend to recover without needing medication. Old people and people with chronic illnesses, such as cardiovascular illnesses, diabetes, respiratory issues or cancer have a higher risk of showing sever symptoms and are urged to seek medical help. Anyone, from all ages, can contract COVID-19 and get seriously ill, or worse, lose their life.',
        description3: '',
        image:'',
        button:'',
        phone:'',
        lien:'' ,
        adresse:'',
        email:"",
    },
    {
        id: 3,
        titre: 'E-COVID-19 ',
        sous_titre: '',
        paragraphe: 'The virus can spread from an infected person’s mouth or nose in small liquid particles when they cough, sneeze, speak, sing or breathe. These particles range from larger respiratory droplets to smaller aerosols. You can be infected by breathing in the virus if you are near someone who has COVID-19, or by touching a contaminated surface and then your eyes, nose or mouth. The virus spreads more easily indoors and in crowded settings.',
        description3: '',
        image:'',
        lien:'' ,
        button:'',
        phone:'',
        adresse:'',
        email:"",
    },

    {
        id: 4,
        titre: 'OUR SERVICES',        
        description3: '',
        sous_titre: '',
        paragraphe: 'Our platform provides services that span from Real Time Social Media Analysis to Data Classification, through Artificial Intelligence and Modeling, we are able to extract data from comments on different social media websites, run that data through our data analysis models, and classify it accordingly. All the information is stored, from the date the comment was posted, to what emotion and topic were extracted from said comment.',
        image:'',
        lien:'' ,
        button:'',
        phone:'',
        adresse:'',
        email:"",
    },
    {
        id: 5,
        titre: 'Get In Touch With Us ',
        sous_titre: '',
    description3: '',
    paragraphe:'Send us your request to join the team of data reviewers so you can help us manage the large flux of data we get daily and if your profile fits, you will receive a personal account with access to all the data and the option to annote data.',
        lien:'' ,
        phone:'+212 (0)530-103000',
        adresse:'Université Internationale de Rabat Technopolis Rabat-Shore Rocade Rabat-Salé 11000 Sala Al Jadida',
        email:'contact@uir.ac.ma ',
        button:'',
        image:'',

    }
]